//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PiesPiesPies.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int SalesID { get; set; }
        public System.DateTime Date { get; set; }
        public int CustomerID { get; set; }
        public int PieID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Pie Pie { get; set; }
    }
}
